# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 31, 17, 23, 27, 743775), verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified On'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 31, 17, 23, 54, 673349), verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified On'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 31, 17, 23, 58, 848), verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified On'),
        ),
        migrations.AlterField(
            model_name='account',
            name='monthly_budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
